@host = http://localhost:5164/api/code

### Запуск кода
POST {{host}}/execution
Content-Type: application/json

{
    "Language": "python",
    "Version": "3.9-slim",
    "Code": "def puk():\n    print('srenk')\npuk()"
}